### ISSUE TITLE
Modern proxying and resizing API

### ISSUE THREAD

**Issue by jnordberg** [steemit/imagehoster#60]
The current image proxy api is limiting the layout options for condenser, a more flexible api is desirable.

Current API:

`/<width>x<height>/<url>`

Proxies the images using the following logic:

```python
image = fetch_remote_image(url)
if width == 0 and height == 0:
    return image
else:
    if width == 0:
        width = orig_width
    if height == 0:
        height = orig_height
    return aspect_downsample(image, long_edge=min(width, height))
```

(simplified, actual implementation has some quirks but that is the intention of it)

## New API proposal

To be run in parallel with the old API to support existing images embedded in blockchain and ease transition in condenser.

`GET /p/<b58_url>`

* `b58_url` - base58 encoded url, base58 is chosen because it is URL-safe and we already have the encoding and decoding libraries in place as they are used for key serialization

Configuration passed with a optional query string, making it easy to extend with additional features without breaking backwards compatibility.

* `width` - image width
* `height` - image height
* `mode` - scaling mode
    * `fit` - default, same behaviour as current api aspect resize to longest edge
    * `cover` - aspect scale with center-weighted crop to exact `width` and `height` given
    * `cover-feature`* - same as cover but cropped around ANN-detected point of interest (eg. a face)
* `format` - output format
    * `match` - default, matches input format
    *  `jpeg`
    * `png`
    * `placeholder-svg`*

*future additions 😉

`width` and `height` will be restricted to predefined ranges (e.g. 10 to 8000 pixels) and the actual output size along with the original image size will be added to the response headers in the format:

```
X-Image-Size: <width>x<height>
X-Original-Image-Size: <orig_width>x<orig_height>
```

### Examples

*`/p/8SzwQbWfyXBo4gGy82jpgqMBFmkGyEfhMLwETxhJnbvQkhXnj7EoB4REy1MffzgHP1rp1HHcxrw37xgr7BjWQeW8krWjc64A7HuiN32ZGP31PDAGqMx`*

![doge](https://user-images.githubusercontent.com/95886/35978056-fa5b06b4-0ce4-11e8-9d82-1dfaf04d3c67.jpg)

*`/p/8SzwQbWfyXBo4gGy82jpgqMBFmkGyEfhMLwETxhJnbvQkhXnj7EoB4REy1MffzgHP1rp1HHcxrw37xgr7BjWQeW8krWjc64A7HuiN32ZGP31PDAGqMx?width=200&height=200&mode=cover`*

![doge_200_200_cover](https://user-images.githubusercontent.com/95886/35977315-11cab148-0ce3-11e8-9867-b73a0ba2d707.png)

*`/p/8SzwQbWfyXBo4gGy82jpgqMBFmkGyEfhMLwETxhJnbvQkhXnj7EoB4REy1MffzgHP1rp1HHcxrw37xgr7BjWQeW8krWjc64A7HuiN32ZGP31PDAGqMx?width=200`*

![doge_200](https://user-images.githubusercontent.com/95886/35978763-dda50b3a-0ce6-11e8-9607-b59333b5dff0.jpg)

**Comment by niouton** [comment]
This would be a very welcome improvement! I'm looking at ways for me to be able to resize images with fit/crop so that my thumbnail always has the same size no matter what the original dimension ratio was.

I've found a couple of freemium services but the major down side I can see with them (other than price potentially if usage reaches paying plans) is that if they close down for whatever reason, then images in my blog posts will be broken forever. I guess the same goes for Steemit's image hoster but I would hope that if they stop maintaining it, they offer an alternative, or this means Steem has become worthless/abandoned, in which case it probably doesn't matter so much.

I've also found an open source library called Thumbor to self host a proxy image service which looks quite advanced too, but I'd have to trust myself to host/maintain it for a long time (which I don't).

In saying that, you might want to look into it as it offers the same api interface to resize /[width]x[height] but also offers all sorts of cool filters, the cropping options you're considering and more.
The library: http://thumbor.readthedocs.io/en/latest/crop_and_resize_algorithms.html
Image resizing/cropping: http://thumbor.readthedocs.io/en/latest/crop_and_resize_algorithms.html
The filters: http://thumbor.readthedocs.io/en/latest/filters.html
There are even extensions to store images in aws s3 and others: http://thumbor.readthedocs.io/en/latest/plugins.html#storages
